export const MILLISECONDS_IN_SECOND = 1_000;
export const SECONDS_IN_MINUTE = 60;
export const MINUTES_IN_HOUR = 60;

export const MILLISECONDS_IN_MINUTE =
  MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE;

export const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * MINUTES_IN_HOUR;

// Precision
export const HUNDREDTHS_IN_SECOND = 100;
export const TIMER_TICK_RATE_MS = 100;
